version: "3.9"

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - CPP_SERVER_PORT=5000
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      - SERVER_PORT=3000
      - CPP_SERVER_HOST=server
      - CPP_SERVER_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - server
